Support externals
datasignstech/pyluca pull request #31
Opened 2023-01-22 13:25 UTC by pskd73

2023-01-22 13:30 UTC, sattyamjjain requested changes

2023-01-22 13:30 UTC, sattyamjjain commented on pyluca/action.py
> +def apply(event: Event, accountant: Accountant, context: dict = None, externals: dict = None):
instead of None, can we set {}

2023-01-22 13:30 UTC, sattyamjjain commented on pyluca/action.py
> +    externals = externals if externals else {}
then we dont need this

2023-01-22 13:32 UTC, sattyamjjain requested changes

2023-01-22 13:32 UTC, sattyamjjain commented on pyluca/action.py
> +def apply(event: Event, accountant: Accountant, context: dict = None, externals: dict = None):
can we use any other name variable,
externals is not giving the actual context

2023-01-22 13:37 UTC, pskd73 commented on pyluca/action.py
> +def apply(event: Event, accountant: Accountant, context: dict = None, externals: dict = None):
PyCharm suggests not to use mutable as a default value.

2023-01-22 13:45 UTC, sameer-639 commented on pyluca/action.py
> +        args = {k: _get_param(v, event, accountant, context) for k, v in action.get('context', {}).items()}
instead of args make it kwargs

2023-01-22 14:08 UTC, sattyamjjain submitted a review, later dismissed

2023-01-22 14:10 UTC, ranjanikrrao approved these changes

2023-01-22 14:16 UTC, sameer-639 approved these changes

2023-01-22 14:24 UTC, sameer-639 approved these changes

2023-01-23 09:09 UTC, ranjanikrrao commented on pyluca/action.py
> +        raise NotImplementedError(f'"{action_type}" is not a valid action type!')
Why double quotes again?

2023-01-23 09:10 UTC, pskd73 commented on pyluca/action.py
> +        raise NotImplementedError(f'"{action_type}" is not a valid action type!')
It is double quotes inside string

2023-01-23 09:10 UTC, ranjanikrrao commented on pyluca/action.py
> +        raise NotImplementedError(f'"{action_type}" is not a valid action type!')
Okay

2023-01-23 09:11 UTC, ranjanikrrao approved these changes

2023-01-23 09:11 UTC, sattyamjjain approved these changes

2023-01-23 10:14 UTC, adithyadinesh96 approved these changes

2023-01-23 10:29 UTC, merged