Adding assertion check to not add backdated journal entries
datasignstech/pyluca pull request #36
Opened 2023-01-31 17:25 UTC by ranjanikrrao

2023-01-31 17:30 UTC, sameer-639 commented on pyluca/accountant.py
> +        assert not any([entry for entry in self.journal.entries if date < entry.date]), f'Backdated journal entries cannot be added'
I guess it should be above amount check

2023-01-31 17:33 UTC, sameer-639 approved these changes

2023-02-01 06:32 UTC, pskd73 requested changes

2023-02-01 06:32 UTC, pskd73 commented on pyluca/journal.py
> +        self.max_date: datetime = None if not entries else max([entry.date for entry in entries])
Lets use `... if len(entries) ...` instead?

2023-02-01 06:32 UTC, pskd73 commented on pyluca/tests/test_accountant.py
> +        accountant = Accountant(Journal(), account_config, 'person2')
We should not initiate Accountant. We are testing Journal, so use only journal

2023-02-01 06:32 UTC, pskd73 commented on pyluca/tests/test_accountant.py
> +
Add more assertions for checking the max_date is correctly maintained by adding more entries cumulatively

2023-02-01 07:01 UTC, pskd73 approved these changes

2023-02-01 07:10 UTC, merged